import { RecordingSettings } from "../../../types";
import {
  VideoCodec,
  VideoQuality,
  VideoStabilization,
} from "../../../types/video";

/**
 * Génère un titre automatique basé sur le contenu
 */
export const generateAutoTitle = (
  contentText: string,
  t: (key: string, options?: any) => string
): string => {
  // Si le contenu est vide, utiliser la date
  if (!contentText.trim()) {
    const now = new Date();
    const formattedDate = now.toLocaleDateString("fr-FR", {
      day: "2-digit",
      month: "2-digit",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
    return (
      t("editor.autogenerated.titlePrefix") +
      " " +
      t("editor.autogenerated.dateFormat", { date: formattedDate })
    );
  }

  // Extraire les premiers mots du contenu (max 5 mots ou 30 caractères)
  const words = contentText.trim().split(/\s+/);
  const firstWords = words.slice(0, 5).join(" ");

  if (firstWords.length <= 30) {
    return firstWords;
  } else {
    return firstWords.substring(0, 27) + "...";
  }
};

/**
 * Nettoie le contenu HTML
 */
export const cleanHtmlContent = (content: string): string => {
  return content
    .replace(/<b>/g, "**")
    .replace(/<\/b>/g, "**")
    .replace(/<i>/g, "*")
    .replace(/<\/i>/g, "*")
    .replace(/<mark>/g, "^")
    .replace(/<\/mark>/g, "^")
    .replace(/<[^>]*>/g, ""); // Supprimer toutes les autres balises HTML
};

/**
 * Paramètres d'enregistrement par défaut
 */
export const getDefaultRecordingSettings = (): RecordingSettings => {
  return {
    // Propriétés requises
    audioEnabled: true,
    videoEnabled: true,
    quality: "high",
    countdown: 3,
    fontSize: 24,
    textColor: "#ffffff",
    horizontalMargin: 0,
    isCompactMode: false,
    // Propriétés optionnelles
    scrollSpeed: 50,
    isMirrored: false,
    isMicEnabled: true,
    isVideoEnabled: true,
    textAlignment: "center",
    textShadow: false,
    showCountdown: true,
    countdownDuration: 3,
    videoQuality: "1080p",
    scrollAreaTop: 15,
    scrollAreaBottom: 20,
    scrollStartLevel: 5,
    videoSettings: {
      codec: VideoCodec.H264,
      quality: VideoQuality["1080p"],
      stabilization: VideoStabilization.auto,
    },
  };
};
