import { SettingCategory, SettingItem } from "./types";

export const getCategories = (t: any): SettingCategory[] => [
  {
    id: "display",
    title: t("help.categories.display.title"),
    icon: "palette",
    color: "#3B82F6",
    description: t("help.categories.display.description"),
  },
  {
    id: "recording",
    title: "🎥 Enregistrement",
    icon: "video",
    color: "#EF4444",
    description: "Qualité vidéo, stabilisation et paramètres de capture",
  },
  {
    id: "security",
    title: "🔐 Sécurité",
    icon: "shield-check",
    color: "#10B981",
    description: "Protection des données et paramètres de confidentialité",
  },
  {
    id: "advanced",
    title: "⚙️ Avancé",
    icon: "cog",
    color: "#8B5CF6",
    description: "Cache, réinitialisation et paramètres techniques",
  },
];

export const getSettingsData = (t: any): SettingItem[] => [
  // Affichage
  {
    id: "themes",
    title: t("help.settings.themes.title"),
    description: t("help.settings.themes.description"),
    icon: "palette",
    color: "#3B82F6",
    category: "display",
    steps: [
      t("help.settings.themes.step1"),
      t("help.settings.themes.step2"),
      "Choisissez parmi : Clair, Sombre, Midnight, Nature, Ocean, Sunset",
      "Le thème s'applique instantanément",
      "Personnalisez les couleurs et transparence si souhaité",
    ],
    tips: t("help.settings.themes.tips"),
  },
  {
    id: "script-display",
    title: "Mode d'Affichage des Scripts",
    description:
      "Changez la présentation de vos scripts (Liste, Stack, Library)",
    icon: "view-list",
    color: "#3B82F6",
    category: "display",
    steps: [
      "Allez dans Paramètres → Section Affichage",
      "Appuyez sur 'Affichage des Scripts'",
      "Choisissez votre mode préféré :",
      "• Liste : Vue traditionnelle en ligne",
      "• Stack : Cartes empilées modernes",
      "• Library : Vue bibliothèque avec aperçus",
      "Le changement s'applique immédiatement",
    ],
    tips: "Le mode Library est idéal pour visualiser rapidement le contenu",
  },
  {
    id: "mirror-mode",
    title: "Activer le Mode Miroir",
    description:
      "Inversez l'affichage pour utilisation avec prompteur physique",
    icon: "mirror",
    color: "#3B82F6",
    category: "display",
    steps: [
      "Paramètres → Section Affichage",
      "Localisez 'Mode Miroir'",
      "Activez le toggle ON/OFF",
      "L'affichage du téléprompteur sera inversé",
      "Idéal pour utilisation avec miroir physique",
    ],
    tips: "Utilisez avec un miroir sans tain pour lecture naturelle face caméra",
  },
  {
    id: "text-shadow",
    title: "Ombre du Texte",
    description: "Améliorez la lisibilité du téléprompteur",
    icon: "format-text",
    color: "#3B82F6",
    category: "display",
    steps: [
      "Paramètres → Section Affichage",
      "Trouvez 'Ombre du Texte'",
      "Activez pour ajouter une ombre subtile",
      "Améliore la lisibilité sur fonds complexes",
      "Particulièrement utile avec des images de fond",
    ],
    tips: "Essentiel si vous utilisez des arrière-plans colorés ou des images",
  },
  {
    id: "fab-style",
    title: "Style du Menu Flottant (FAB)",
    description: "Choisissez parmi 4 designs de menu flottant",
    icon: "gesture-tap-button",
    color: "#3B82F6",
    category: "display",
    steps: [
      "Paramètres → Style du Menu Flottant",
      "Sélectionnez votre design préféré :",
      "• Classique : Barre horizontale traditionnelle",
      "• Cartes Empilées : Déploiement avec rotation",
      "• Orbital : Boutons qui orbitent autour du centre",
      "• Dock Style : Style macOS avec effet zoom",
      "Le changement s'applique immédiatement",
    ],
    tips: "Le style Orbital est le plus efficace pour un accès rapide",
  },

  // Enregistrement
  {
    id: "video-quality",
    title: "Configurer la Qualité Vidéo",
    description: t("help.settingsGuide.videoQualityDescription"),
    icon: "video-high-definition",
    color: "#EF4444",
    category: "recording",
    steps: [
      "Paramètres → Section Enregistrement",
      "Appuyez sur 'Qualité Vidéo'",
      "Sélectionnez la résolution :",
      "• 720p (HD) - Économie d'espace",
      "• 1080p (Full HD) - Standard recommandé",
      "• 2160p (4K) - Qualité maximale",
      "Considérez l'espace de stockage disponible",
    ],
    tips: "1080p offre le meilleur compromis qualité/taille pour les réseaux sociaux",
    warning: "4K consomme beaucoup d'espace de stockage et de batterie",
  },
  {
    id: "stabilization",
    title: "Stabilisation Vidéo",
    description: "Réduisez les tremblements pour des vidéos plus fluides",
    icon: "image-filter-center-focus",
    color: "#EF4444",
    category: "recording",
    steps: [
      "Paramètres → Section Enregistrement",
      "Localisez 'Stabilisation'",
      "Choisissez le mode :",
      "• Auto - Détection intelligente",
      "• Standard - Stabilisation normale",
      "• Cinématique - Mouvement fluide",
      "• Désactivé - Aucune stabilisation",
      "Testez avec votre style d'enregistrement",
    ],
    tips: "Le mode Auto s'adapte automatiquement à vos mouvements",
  },
  {
    id: "countdown",
    title: "Compte à Rebours",
    description: "Configurez le délai avant démarrage de l'enregistrement",
    icon: "timer",
    color: "#EF4444",
    category: "recording",
    steps: [
      "Paramètres → Section Enregistrement",
      "Appuyez sur 'Compte à Rebours'",
      "Sélectionnez la durée :",
      "• 3 secondes - Démarrage rapide",
      "• 5 secondes - Standard",
      "• 10 secondes - Plus de temps de préparation",
      "Le compte à rebours s'affichera avant chaque enregistrement",
    ],
    tips: "5 secondes est idéal pour se positionner et commencer à lire",
  },
  {
    id: "codec-settings",
    title: "Paramètres de Codec (iOS ProRes)",
    description: "Configurez l'encodage vidéo pour la qualité maximale",
    icon: "file-video",
    color: "#EF4444",
    category: "recording",
    steps: [
      "Paramètres → Section Enregistrement (iOS uniquement)",
      "Si disponible, sélectionnez 'Codec'",
      "Choisissez entre :",
      "• ProRes 422 - Équilibré",
      "• ProRes 4444 - Qualité maximale",
      "Nécessite un appareil compatible",
      "Fichiers plus volumineux mais qualité professionnelle",
    ],
    tips: "ProRes est idéal pour l'édition professionnelle",
    warning: "ProRes génère des fichiers très volumineux",
  },

  // Sécurité
  {
    id: "enhanced-security",
    title: "Sécurité Renforcée",
    description: "Activez la protection supplémentaire des données",
    icon: "shield-plus",
    color: "#10B981",
    category: "security",
    steps: [
      "Paramètres → Section Sécurité",
      "Localisez 'Sécurité Renforcée'",
      "Activez le toggle",
      "Effets activés :",
      "• Chiffrement renforcé des données",
      "• Authentification plus fréquente",
      "• Logs de sécurité détaillés",
      "• Protection contre les accès non autorisés",
    ],
    tips: "Recommandé pour les contenus sensibles ou professionnels",
  },
  // Élément biométrie supprimé
  {
    id: "data-encryption",
    title: "Chiffrement des Données",
    description: "Protégez vos fichiers avec un chiffrement avancé",
    icon: "lock",
    color: "#10B981",
    category: "security",
    steps: [
      "Paramètres → Section Sécurité",
      "Activez 'Chiffrement des Données'",
      "Tous vos scripts seront chiffrés",
      "Les vidéos peuvent être chiffrées (option)",
      "Sauvegarde sécurisée dans le cloud",
      "Mot de passe de récupération requis",
    ],
    warning: "Gardez précieusement votre mot de passe de récupération",
  },
  {
    id: "privacy",
    title: "Gestion de la Confidentialité",
    description: t("help.settingsGuide.privacyDescription"),
    icon: "shield-lock",
    color: "#3B82F6",
    category: "security",
    steps: [
      t("help.settingsGuide.securitySectionStep"),
      "Configurer le verrouillage automatique",
    ],
  },

  // Avancé
  {
    id: "ai-cache",
    title: "Gestion du Cache IA",
    description: "Optimisez les performances et libérez l'espace",
    icon: "robot",
    color: "#8B5CF6",
    category: "advanced",
    steps: [
      "Paramètres → Section Cache IA",
      "Visualisez la taille du cache actuel",
      "Appuyez sur 'Vider le cache' si nécessaire",
      "Confirmez l'action",
      "L'historique des conversations IA sera supprimé",
      "Les performances peuvent s'améliorer",
    ],
    tips: "Videz le cache si l'IA devient lente ou si vous manquez d'espace",
  },
  {
    id: "reset-settings",
    title: "Réinitialiser les Paramètres",
    description: "Restaurez la configuration par défaut",
    icon: "refresh",
    color: "#8B5CF6",
    category: "advanced",
    steps: [
      "Paramètres → Section Réinitialisation",
      "Appuyez sur 'Réinitialiser les paramètres'",
      "Lisez attentivement l'avertissement",
      "Confirmez l'action",
      "Tous les paramètres reviennent aux valeurs par défaut",
      "Vos scripts et vidéos sont conservés",
    ],
    warning:
      "Cette action est irréversible. Notez vos paramètres importants avant.",
  },
  {
    id: "language-settings",
    title: "Changer la Langue",
    description: "Interface disponible en 12 langues",
    icon: "translate",
    color: "#8B5CF6",
    category: "advanced",
    steps: [
      "Paramètres → Section Langue",
      "Sélectionnez parmi 12 langues disponibles :",
      "🇫🇷 Français, 🇬🇧 English, 🇪🇸 Español",
      "🇩🇪 Deutsch, 🇮🇹 Italiano, 🇵🇹 Português",
      "🇷🇺 Русский, 🇨🇳 中文, 🇯🇵 日本語",
      "🇰🇷 한국어, 🇮🇳 हिन्दी",
      "L'interface se met à jour instantanément",
    ],
    tips: "Le changement affecte toute l'interface mais pas vos scripts existants",
  },
  {
    id: "notifications-settings",
    title: "Paramètres de Notifications",
    description: "Contrôlez les alertes et messages de l'application",
    icon: "bell-ring",
    color: "#EC4899",
    category: "advanced",
    steps: [
      "Paramètres → Section Alertes",
      "Configurez selon vos préférences :",
      "• Masquer toutes les alertes (toggle principal)",
      "• Alertes de sauvegarde",
      "• Confirmations de réinitialisation",
      "• Messages d'erreur",
      "• Notifications de bienvenue",
      "Ajustez la fréquence des messages",
    ],
    tips: "Désactivez les alertes de sauvegarde pour une expérience plus fluide",
  },
  {
    id: "cache",
    title: "Gestion du Cache",
    description: t("help.settingsGuide.cacheDescription"),
    icon: "database-cog",
    color: "#10B981",
    category: "advanced",
    steps: [
      t("help.settingsGuide.cacheSectionStep"),
      "Vider le cache des modèles IA",
      "Configurer le nettoyage automatique",
    ],
  },
  {
    id: "getting-started",
    category: "general",
    title: t("help.gettingStarted.title"),
    description: t("help.gettingStarted.description"),
    icon: "rocket-launch",
    color: "#8B5CF6",
    steps: [
      t("help.settingsGuide.openSettingsStep"),
      t("help.gettingStarted.configureProviders"),
      t("help.gettingStarted.startCreating"),
    ],
  },
];
