export const LAYOUT_CONTROLS = {
  messageWidth: {
    label: "Largeur des bulles",
    icon: "arrow-expand-horizontal",
    unit: "%",
    min: 60,
    max: 95,
    step: 5,
    presets: [70, 80, 85, 90],
  },
  messageHeight: {
    label: "Taille du texte",
    icon: "format-size",
    unit: "x",
    min: 0.8,
    max: 1.5,
    step: 0.1,
    presets: [0.9, 1.0, 1.1, 1.2],
  },
  messageGap: {
    label: "Espacement",
    icon: "arrow-expand-vertical",
    unit: "px",
    min: 4,
    max: 32,
    step: 2,
    presets: [8, 12, 16, 20],
  },
  paddingHorizontal: {
    label: "Marges horizontales",
    icon: "border-horizontal",
    unit: "px",
    min: 8,
    max: 24,
    step: 2,
    presets: [12, 16, 18, 20],
  },
  paddingVertical: {
    label: "Marges verticales",
    icon: "border-vertical",
    unit: "px",
    min: 6,
    max: 20,
    step: 2,
    presets: [8, 12, 16, 18],
  },
} as const;
